name       : haskell-th-lift-instances
version    : 0.1.17
release    : 3
source     :
    - https://hackage.haskell.org/package/th-lift-instances-0.1.17/th-lift-instances-0.1.17.tar.gz : 45353a114f51614503c3974a062817fd8f878e5650705e5bdc29b3060c91a94c
license    : BSD-3-Clause
component  : programming.haskell
summary    : Most data types in haskell platform do not have Lift instances. This package provides orphan instances for containers, text, bytestring and vector.
description: |
    Most data types in haskell platform do not have Lift instances. This package provides orphan instances for containers, text, bytestring and vector.
builddeps  :
    - haskell-cabal-install
    - haskell-th-lift-devel
    - haskell-vector-devel
rundeps    :
    - devel:
        - haskell-th-lift-devel
        - haskell-vector-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
