name       : haskell-th-lift-instances
version    : 0.1.11
release    : 2
source     :
    - http://hackage.haskell.org/package/th-lift-instances-0.1.11/th-lift-instances-0.1.11.tar.gz : 1da46afabdc73c86f279a0557d5a8f9af1296f9f6043264ba354b1c9cc65a6b8
license    : BSD-3-Clause
component  : programming.haskell
summary    : Most data types in haskell platform do not have Lift instances. This
    package provides orphan instances for containers, text, bytestring and vector.
description: "Most data types in haskell platform do not have Lift instances. This\
    \ package provides orphan instances for containers, text, bytestring and vector.\
    \ \n"
builddeps  :
    - haskell-cabal-install
    - haskell-text
    - haskell-th-lift
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
